# Generated by Django 4.2.27 on 2026-01-15 07:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.CharField(db_index=True, max_length=64)),
                ('action', models.CharField(max_length=32)),
                ('entity_name', models.CharField(max_length=128)),
                ('entity_id', models.CharField(max_length=64)),
                ('user_id', models.CharField(blank=True, max_length=64, null=True)),
                ('changes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'audit_logs',
            },
        ),
    ]
